# Server
server.port=${SERVER_PORT}
spring.application.name=${APP_NAME}

# DataSource
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=${DDL_AUTO}
spring.jpa.show-sql=${SHOW_SQL}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

# Redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

# Actuator
management.endpoints.web.exposure.include=health,info

# ZooKeeper
zookeeper.connect-string=${ZOOKEEPER_CONNECT_STRING}
zookeeper.connection-timeout-ms=${ZOOKEEPER_CONNECTION_TIMEOUT_MS}
zookeeper.worker-node-path=${ZOOKEEPER_WORKER_NODE_PATH}

# Snowflake
snowflake.fallback-worker-id=${SNOWFLAKE_FALLBACK_WORKER_ID}

# App
app.base-url=${APP_BASE_URL}
app.short-url-length=${APP_SHORT_URL_LENGTH}
app.default-expiry-days=${APP_DEFAULT_EXPIRY_DAYS}

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

spring.security.oauth2.client.registration.google.scope=email,profile